plugins {
    id 'com.gradleup.shadow'
}

loom {
    forge {
        mixinConfig "o123456789.mixins.json"
        mixinConfig "o123456789_forge.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    modImplementation "curse.maven:emi-580555:6420945"
    modImplementation "curse.maven:applied-energistics-2-223794:6763576"
    modImplementation "curse.maven:guideme-1173950:6679102"
    modImplementation "curse.maven:sophisticated-core-618298:6759791"
    modImplementation "curse.maven:sophisticated-backpacks-422301:6788668"
    modImplementation "curse.maven:curios-309927:6418456"
    modImplementation "software.bernie.geckolib:geckolib-forge-1.20.1:4.7.3"
    implementation "com.eliotlash.mclib:mclib:20"
    forgeRuntimeLibrary("com.eliotlash.mclib:mclib:20")
    modImplementation "curse.maven:ars-nouveau-401955:6688854"

    implementation(include("io.github.llamalad7:mixinextras-forge:0.4.1"))
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    from project(":common").sourceSets.main.resources

    inputs.property 'version', project.version

    filesMatching('META-INF/mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'signing'
    apply plugin: 'idea'

    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    java.withSourcesJar()
    java.withJavadocJar()
    javadoc.options.addStringOption('Xdoclint:none', '-quiet')

    repositories {
        mavenCentral()
        mavenLocal()
        flatDir {
            dirs 'libs'
        }
    }
}